name: siteSlider
author: rron
category: Interface
tags: [interface, slider, window, animation]
#docs: http://github.com/rron/siteSlider/blob/master/README.md
#demo: http://github.com/rron/siteSlider/tree/master/demo
#current: 1.0